# Generated by Django 3.2.15 on 2023-02-08 10:43

from django.db import migrations, models
import django.db.models.deletion
import orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('uuid', models.CharField(default=orchestrator.models._uuidstr, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default='manager', max_length=255)),
                ('status', models.CharField(default='A', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='apis',
            field=models.JSONField(blank=True, default=orchestrator.models._default_required_apis),
        ),
        migrations.AlterField(
            model_name='module',
            name='args',
            field=models.JSONField(blank=True, default=orchestrator.models._emptylist),
        ),
        migrations.AlterField(
            model_name='module',
            name='channels',
            field=models.JSONField(blank=True, default=orchestrator.models._emptylist),
        ),
        migrations.AlterField(
            model_name='module',
            name='env',
            field=models.JSONField(blank=True, default=orchestrator.models._emptylist),
        ),
        migrations.AlterField(
            model_name='module',
            name='fault_crash',
            field=models.CharField(default='ignore', max_length=16),
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='filetype',
            field=models.CharField(default='WA', max_length=8),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='module', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orchestrator.runtime'),
        ),
        migrations.AlterField(
            model_name='module',
            name='peripherals',
            field=models.JSONField(blank=True, default=orchestrator.models._emptylist),
        ),
        migrations.AlterField(
            model_name='module',
            name='resources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default=orchestrator.models._uuidstr, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='aot_target',
            field=models.CharField(blank=True, default='{}', max_length=500),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.JSONField(blank=True, default=orchestrator.models._default_runtime_apis),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='ka_interval_sec',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='ka_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='max_nmodules',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='name',
            field=models.CharField(default='runtime', max_length=255),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='page_size',
            field=models.IntegerField(default=65536),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='platform',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='runtime_type',
            field=models.CharField(default='linux', max_length=16),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='status',
            field=models.CharField(default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='uuid',
            field=models.CharField(default=orchestrator.models._uuidstr, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='runtime',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orchestrator.manager'),
        ),
    ]
