# Generated by Django 3.2.15 on 2023-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_auto_20230214_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='filename',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='env',
        ),
        migrations.RemoveField(
            model_name='module',
            name='peripherals',
        ),
        migrations.RemoveField(
            model_name='module',
            name='resources',
        ),
        migrations.AlterField(
            model_name='runtime',
            name='max_nmodules',
            field=models.IntegerField(default=1),
        ),
    ]
