#!/bin/bash

# some mqqt test calls
# each message to arts should have a random object_id (a uuid v4) to be generated by the client; 
# the client can use these to match responses to that request
######

# create a new runtime
mosquitto_pub -h 'oz.andrew.cmu.edu' -t 'realm/proc/reg' -m '{ "object_id": "64c41912-4daf-11ea-b77f-2e728ce88821", "action": "create", "type": "arts_req", "data": { "type":"runtime", "name": "runtime1" } }'

# delete a runtime (need to pass an existing runtime uuid in data.object_id)
mosquitto_pub -h 'oz.andrew.cmu.edu' -t 'realm/proc/reg' -m '{ "object_id": "64c41912-4daf-11ea-b77f-2e728ce88465", "action": "delete", "type": "arts_req", "data": { "type":"runtime", "object_id": "bff0f0b4-5fa5-400f-b492-79c6566df6c2" } }'

# create a new module 
mosquitto_pub -h 'oz.andrew.cmu.edu' -t 'realm/proc/control' -m '{ "object_id":"64c41912-4daf-11ea-b77f-2e728af27492", "action": "create", "type": "arts_req", "data": { "type":"module", "name": "module1", "filename": "test.wasm", "fileid":"1mcJhBvnNqs1CpNsZG2QUjhk3_8SS7Q7U", "filetype": "PY", "args": ""}}'

# delete a module (need to pass an existing module uuid in data.object_id)
mosquitto_pub -h 'oz.andrew.cmu.edu' -t 'realm/proc/reg' -m '{ "object_id": "64c41912-4daf-11ea-b77f-2e728ce88465", "action": "delete", "type": "arts_req", "data": { "type":"module", "object_id": "35242a8f-134a-4f04-b0cf-4259c55092c7" } }'
