# Generated by Django 3.0.3 on 2020-02-10 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0002_auto_20200210_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts_core.Module')),
            ],
        ),
    ]
