# Generated by Django 3.0.3 on 2020-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0006_auto_20200211_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
