# Generated by Django 3.0.3 on 2020-02-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0009_auto_20200213_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='args',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
