# Generated by Django 3.0.3 on 2020-02-14 14:16

import arts_core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0011_auto_20200214_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='filetype',
            field=models.CharField(choices=[(arts_core.models.FileType['WA'], 'WASM'), (arts_core.models.FileType['PY'], 'PYTHON')], default='WASM', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runtime',
            name='max_nmodules',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='runtime',
            name='nmodules',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runtime',
            name='apis',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='arts_core.API'),
            preserve_default=False,
        ),
    ]
