# Generated by Django 3.0.3 on 2020-02-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0014_runtime_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='arts_core.API'),
        ),
    ]
