# Generated by Django 3.0.3 on 2020-02-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0015_auto_20200214_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filetype',
            field=models.CharField(choices=[('WA', 'WASM'), ('PY', 'PYTHON')], default='WA', max_length=10),
        ),
    ]
