# Generated by Django 3.0.3 on 2020-02-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0016_auto_20200214_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='fileid',
            field=models.CharField(default='a_file_id', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.CharField(default='wasi:snapshot_preview1', max_length=10),
        ),
        migrations.DeleteModel(
            name='API',
        ),
    ]
