# Generated by Django 3.2.15 on 2022-08-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='alive',
        ),
    ]
