# Generated by Django 3.2.14 on 2022-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='platform',
            field=models.JSONField(blank=True, help_text='Platform manifest', null=True),
        ),
    ]
