# Generated by Django 3.2.15 on 2022-08-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_runtime_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='max_nmodules',
            field=models.IntegerField(default=100, help_text='Max number of modules suppoprted by runtime'),
        ),
    ]
