# Generated by Django 3.2.15 on 2022-08-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_module_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='fault_crash',
            field=models.CharField(default='ignore', help_text='Fault handling behavior on crash (ignore or restart).', max_length=16),
        ),
    ]
