# Generated by Django 3.1.14 on 2022-01-29 19:06

from django.db import migrations, models
import uuid
import wasm_files.file_handler


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WASMFiles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('wasm_file', models.FileField(upload_to=wasm_files.file_handler.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
