name: Release to Docker Hub

on:
  release:
    types:
      - created
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ steps.docker_build.context }}/arts-main/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_release.outputs.tag_name }} 

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
