# Generated by Django 3.0.3 on 2020-02-10 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Runtimes',
            new_name='Runtime',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts_core.Runtime')),
            ],
        ),
    ]
