# Generated by Django 3.1.14 on 2022-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='affinity',
        ),
        migrations.RemoveField(
            model_name='module',
            name='period',
        ),
        migrations.RemoveField(
            model_name='module',
            name='runtime',
        ),
        migrations.AddField(
            model_name='module',
            name='resources',
            field=models.JSONField(blank=True, help_text='Resource reservation (runtime/period with SCHED_DEADLINE)', null=True),
        ),
    ]
