# Generated by Django 3.1.14 on 2022-05-25 19:50

import arts_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Optional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.JSONField(blank=True, default=arts_core.models._default_runtime_apis, help_text='Supported APIs.'),
        ),
    ]
