# Generated by Django 3.0.3 on 2020-02-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0003_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_from',
        ),
    ]
