# Generated by Django 3.0.3 on 2020-02-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0004_remove_link_link_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_from', to='arts_core.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='link_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_to', to='arts_core.Module'),
            preserve_default=False,
        ),
    ]
