# Generated by Django 3.0.3 on 2020-02-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0005_auto_20200210_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arts_core.Runtime'),
        ),
    ]
