# Generated by Django 3.0.3 on 2020-02-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0012_auto_20200214_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtime',
            name='apis',
        ),
    ]
