# Generated by Django 3.0.3 on 2020-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0017_auto_20200219_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.CharField(blank=True, default='wasi:snapshot_preview1', max_length=10),
        ),
    ]
