# Generated by Django 3.0.3 on 2020-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0018_auto_20200219_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='stdin_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='stdout_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='args',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='fileid',
            field=models.CharField(default='afileid', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(default='afile.wasm', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='amodule', max_length=255),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.CharField(blank=True, default='wasi:snapshot_preview1', max_length=500),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='name',
            field=models.CharField(default='aruntime', max_length=255),
        ),
    ]
