# Generated by Django 3.0.3 on 2020-02-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0019_auto_20200219_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='stdin_topic',
        ),
        migrations.RemoveField(
            model_name='module',
            name='stdout_topic',
        ),
    ]
