# Generated by Django 3.0.7 on 2020-08-25 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0024_auto_20200622_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='apis',
            field=models.CharField(blank=True, default='wasi:snapshot_preview1', max_length=500),
        ),
        migrations.AddField(
            model_name='runtime',
            name='ka_interval_sec',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='runtime',
            name='ka_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='arts_core.Runtime'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.CharField(blank=True, default='wasi:snapshot_preview1 wasi:unstable wasi:core wasi:clock wasi:environ wasi:sock wasi:args wasi:fd wasi:path wasi:poll wasi:proc wasi:random wasi:sched wasi:sock python:python3', max_length=500),
        ),
    ]
