# Generated by Django 3.0.7 on 2020-10-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0025_auto_20200825_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='args',
            field=models.CharField(blank=True, default=[''], max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='channels',
            field=models.CharField(blank=True, default=[''], max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='env',
            field=models.CharField(blank=True, default=[''], max_length=10000),
        ),
    ]
