# Generated by Django 3.0.7 on 2020-10-22 05:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0026_auto_20201012_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='channels',
            field=jsonfield.fields.JSONField(),
        ),
    ]
