# Generated by Django 3.0.7 on 2020-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0027_auto_20201022_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='peripherals',
            field=models.CharField(blank=True, default=[''], max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='channels',
            field=models.CharField(blank=True, default=[''], max_length=10000),
        ),
    ]
