# Generated by Django 3.0.7 on 2020-11-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0028_auto_20201112_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='page_size',
            field=models.IntegerField(default=65536),
        ),
        migrations.AlterField(
            model_name='module',
            name='apis',
            field=models.CharField(blank=True, default='["wasi:snapshot_preview1"]', max_length=500),
        ),
    ]
