# Generated by Django 3.0.7 on 2020-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0029_auto_20201112_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='apis',
            field=models.CharField(blank=True, default=['wasi:snapshot_preview1'], max_length=500),
        ),
    ]
