# Generated by Django 3.0.14 on 2021-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0031_auto_20210420_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='apis',
            field=models.CharField(blank=True, default='["wasi:snapshot_preview1"]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='module',
            name='args',
            field=models.CharField(blank=True, default='[]', max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='channels',
            field=models.CharField(blank=True, default='[]', max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='env',
            field=models.CharField(blank=True, default='[]', max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='peripherals',
            field=models.CharField(blank=True, default='[]', max_length=10000),
        ),
    ]
