# Generated by Django 3.1.13 on 2022-01-07 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arts_core', '0032_auto_20211115_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='runtime_type',
            field=models.CharField(default='linux', help_text='Runtime type (browser, linux, embedded)', max_length=16),
        ),
        migrations.AlterField(
            model_name='module',
            name='apis',
            field=models.TextField(blank=True, default='["wasi:snapshot_preview1"]', help_text='APIs required by the module.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='args',
            field=models.TextField(blank=True, default='[]', help_text='Arguments to pass to the module at startup.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='channels',
            field=models.TextField(blank=True, default='[]', help_text='Channels to open at startup.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='env',
            field=models.TextField(blank=True, default='[]', help_text='Environment path to pass to the module at startup.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='fileid',
            field=models.CharField(help_text='File ID (required).', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(help_text='Program file (required).', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='filetype',
            field=models.CharField(choices=[('WA', 'WASM'), ('PY', 'PYTHON')], default='WA', help_text='File type (PY, WA)', max_length=16),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='module', help_text='Module short name (len < 255).', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent runtime (runtime where the module is running', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='arts_core.runtime'),
        ),
        migrations.AlterField(
            model_name='module',
            name='peripherals',
            field=models.TextField(blank=True, default='[]', help_text='Required peripherals.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Module UUID.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='apis',
            field=models.CharField(blank=True, default='wasi:snapshot_preview1 wasi:unstable wasi:core wasi:clock wasi:environ wasi:sock wasi:args wasi:fd wasi:path wasi:poll wasi:proc wasi:random wasi:sched wasi:sock python:python3', help_text='Supported APIs.', max_length=500),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='ka_interval_sec',
            field=models.IntegerField(default=60, help_text='Keepalive interval (seconds)'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='ka_ts',
            field=models.DateTimeField(auto_now_add=True, help_text='Last keepalive timestamp'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='max_nmodules',
            field=models.IntegerField(default=3, help_text='Maximum number of modules (todo: replace)'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='name',
            field=models.CharField(default='runtime', help_text='Runtime short name (len <= 255).', max_length=255),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='nmodules',
            field=models.IntegerField(default=0, help_text='Current number of modules (todo: replace)'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='page_size',
            field=models.IntegerField(default=65536, help_text='WASM pagesize. Default = 64KiB. Memory-constrained embedded runtimes can use smaller page size of 4KiB.'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the runtime was updated/created'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Runtime UUID.', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
