'''
Django settings for arts_api project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
'''

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_DEFINED_DURING_DEPLOYMENT'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'arts_core.apps.ArtsCoreConfig',
    'wasm_files'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'arts_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(__file__), 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arts_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Static root
STATIC_ROOT = "./public"

# Rest framework

REST_FRAMEWORK = {
    # When you enable API versioning, the request.version attribute will contain a string
    # that corresponds to the version requested in the incoming client request.
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    # Permission settings
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    # Authentication settings
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# JWT settings
JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
    'rest_framework_jwt.utils.jwt_encode_handler',

    'JWT_DECODE_HANDLER':
    'rest_framework_jwt.utils.jwt_decode_handler',

    'JWT_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_payload_handler',

    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',

    'JWT_RESPONSE_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_response_payload_handler',

    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,

    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),

    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,
}

# pubsub settings
PUBSUB = {
	'mqtt_server': { 'host': 'arena-dev1.conix.io', 'port': 1883, 'ws_port': 9001},
    'mqtt_username': 'cli',
    'mqtt_password': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGkiLCJzdWJzIjpbIiMiXSwicHVibCI6WyIjIl0sImlhdCI6MTYxNzgwMjAwMCwiZXhwIjoxNjQ5MzM4MDAwfQ.Dsx9W1u1TuYFCjMZ4GF6J_dAAmD1apU5cW-T_qkZwjLTc2j2qPb-Nb2_NPes-RaS8uV-AKwOlZ6eKrfDHUzJBLPbM48bq2WsDPuZu-7G-7iVOvSXZNtR7qDbdZODiaZmAUOPomq3haFpQw56WFx2Y2FQ6LuLas5QnFOK0ZrjCAGSeY5MRSsugqKdOoeP7lFFo5BllTsUWmsgf0daIRytlgy1bkD0yM8burDK8pR9QZJhBKGTrr27zjAEq78DANR0__PFAwhSB5D0dFmUOHSarDyt2eQkG1iBup13ho8TOvQTq5-OgImRXYbgeo6_552X6FKPI1TSDQ34jE9KUg1ZhixqvqcZYXaHv7Pmxdn9HT5uArRL3edyix53K_fOnrgBacytReca1RQzagJiX6kgx9vO-VtUQmAmachmH1P3llJ9KFGMraUwX1ONlyhCJUEP_2groRwjiMIaGFww1h_qW_llBntN1oVQzA4qZ_fCpDAQ__OIRu48VTnkttPJ_OShwFMZVWpEnQCNFuOMmOiOdwqie-ohyndYcq3fACJxme4cDXzra_Ee0zyvC6WdVbs_df3CxkuzCuDp3EkKdyk-qQJC1OfijMaOIdBv89eM9JZA0UpxzXVY5auwmxo4_vmfhpNUKqHoMZgnRHh2D5EsajfM5opZzJYAwLJDmHwKKq0',
	'subscribe_topics': [
		{ 'name': 'reg', 'topic': 'test/proc/reg', 'on_message': 'on_reg_message'},
		{ 'name': 'ctl', 'topic': 'test/proc/control', 'on_message': 'on_ctl_message' },
		{ 'name': 'dbg', 'topic': 'test/proc/debug', 'on_message': 'on_dbg_message' },
        { 'name': 'keepalive', 'topic':    'test/proc/keepalive', 'on_message': 'on_keepalive_message' }
	]
}
